version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_tasks
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./back
    container_name: nest_api
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: minhasenha
      DB_NAME: tasksdb
      PORT: 3000
      HOST_API: http://localhost:3000/api
      JWT_SECRET: secret
    depends_on:
      - postgres

  front:
    build:
      context: ./front
    container_name: react_front
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3001:5173"
    environment:
      VITE_API_URL: http://localhost:3000/api
    depends_on:
      - api


volumes:
  postgres_data:
  